### ISSUE TITLE
How to measure F-score?

### ISSUE THREAD

**Issue by D4nihu** [Thijsvanede/DeepLog#11]
When I tried to run the example_hdfs file, in the "Check for anomalies" section, I got 0 False positives normal and 0 True positives abnormal as a result almost every time. In the file I added these lines, but I got pretty poor results:
```
TN = 0
FN = 0

for i in range(len(y_test)):
    if(y_test[i].item() == (y_pred_normal[i][0].item())
    or y_test[i].item() == (y_pred_normal[i][1].item())
    or y_test[i].item() == (y_pred_normal[i][2].item())):
        TN+=1
    else:
        FN+=1


TP = 0
FP = 0

for i in range(len(y_test_anomaly)):
    if(y_test_anomaly[i].item() == (y_pred_anomaly[i][0].item())
    or y_test_anomaly[i].item() == (y_pred_anomaly[i][1].item())
    or y_test_anomaly[i].item() == (y_pred_anomaly[i][2].item())):
        TP+=1
    else:
        FP+=1

print("True negative: ", TN, "False negative: ", FN)
print("True positive: ", TP, "False positive: ", FP)

PREC = TP / (TP + FP)
SENS = TP / (TP + FN)
F = 2 * (PREC * SENS) / (PREC + SENS)

print("\nF-score: ", F)
```
Result:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/56605527/178444973-e135b557-c775-4ecb-ab74-dcfd4506b4dd.png">
(I deleted some lines from the hdfs_test_normal file to load it faster.)

It is possible that I don't understand the DeepLog enough yet, pls correct me if I did something wrong.

**Comment by Thijsvanede** [comment]
I have updated the `example_hdfs.py` (https://github.com/Thijsvanede/DeepLog/blob/master/examples/example_hdfs.py) code to print the classification report (which also computes the F1-score). Please have a look at whether that solves your problem.

Two other things that have changed:
- I set the `k` value of `predict` to `9`, which is what the original DeepLog paper suggests.
- Make sure you have the latest version (either via `pip` or the last git version) as there was a major bug in the code until two weeks ago.

Please let me know if you need clarification regarding the new `example_hdfs.py` script.
