### ISSUE TITLE
parameters anomaly detection model

### ISSUE THREAD

**Issue by shoaib-intro** [Thijsvanede/DeepLog#12]
hey, i tried to understand your repo many time but did not understand pretty well even from your documentation as you are not taking directly parsed input do some kind of pre-processing. 
have you worked on  **parameters anomaly detection** models and if workflow model?

**Comment by Thijsvanede** [comment]
I am sorry, but I am not sure if I understand your question.
This implementation can parse security events given in `.txt` or `.csv` format as specified here: https://deeplog.readthedocs.io/en/latest/reference/preprocessor.html#formats

If you have logs in a different format, you will have convert the logs yourself into one of the supported formats.
For the evaluation on the HDFS dataset, we used the already converted logs in `.txt` form found here: https://github.com/wuyifan18/DeepLog/tree/master/data

**Comment by shoaib-intro** [comment]
what about prameter anomaly detection did you implemented that part ?

**Comment by Thijsvanede** [comment]
No, this library only implements the `Log Key Anomaly Detection` model. I will probably not add the `Parameter Value Anomaly Detection model` myself, but feel free to send me a pull request if you decide to implement it yourself and want it added to the library.
