### ISSUE TITLE
About the Performance..

### ISSUE THREAD

**Issue by Sun-HR02** [Thijsvanede/DeepLog#18]
Thank you for the code. 

I'm trying to learn Deeplog with the original paper and your code. However, the F1 score seems to be really poor.

```log
Classification report - anomalies
              precision    recall  f1-score   support

      Normal     0.9879    0.5347    0.6938  10792214
     Anomaly     0.0409    0.7513    0.0775    284818

    accuracy                         0.5402  11077032
   macro avg     0.5144    0.6430    0.3857  11077032
weighted avg     0.9635    0.5402    0.6780  11077032

```
I trained for 100 epochs and kept other parameters not changed.

**Comment by Thijsvanede** [comment]
The code in this repository only implements DeepLog's `Log Key Anomaly Detection model`, not the `Parameter Value Anomaly Detection model`. I cannot comment on the difference in performance with respect to the DeepLog paper, for that you would have to contact the original authors of the paper.

Good luck with the rest of your work!

**Comment by Sun-HR02** [comment]
Thank you for the reply. Currently most of Deeplog implements don't contain Parameter Value AD. I noticed that the bad performance for this project may attribute to sampling process. Subsequence sampled from `_normal` overwhelm those from `_abnormal`, making TN and FP really huge. Consequently the Precision drops caused by huge FP. 

Anyway, thank you for the project. It helps a lot in my work.
