### ISSUE TITLE
How to update the model

### ISSUE THREAD

**Issue by OutOfBoundCats** [Thijsvanede/DeepLog#3]
Hi sir

i went through your paper and saw you have mentioned y. 

_If user reports that this is a false positive, DeepLog
is able to use the following input-output pair {k1, k2, k3 → k2}
to update the weights of its model to learn this new pattern. So
that next time given history sequence {k1, k2, k3},_ 

can you please help in answering how to do it

**Comment by Thijsvanede** [comment]
Hi OutOfBoundCats,

Before answering your question, I just want to clarify that I am not the author of the DeepLog paper, I merely provide an implementation that we used during the evaluation of our own paper DeepCASE.

We did not implement any update function in this repository.
However, when you would like to update the model, you can simply further train it with the new examples.
