### ISSUE TITLE
predict values

### ISSUE THREAD

**Issue by krishna213** [Thijsvanede/DeepLog#4]
from same above example for which preproccessing is shown 
y_pred, confidence = deeplog.predict() gives output in torch.tensor() also evertimes its giving different values in tensor. eg. [127],
        [127],
        [127],
        [127]
how to get actual values like anomaly or not whenever new line is passed or same sample is passed for prediction?

**Comment by Thijsvanede** [comment]
I have added a new `example_hdfs.py` file in the `/examples/` directory that gives an example on how to perform anomaly detection using the HDFS dataset

**Comment by krishna213** [comment]
yeah that helped
1) for according to this example predict will state 1 or 2 but when i ran this it was giving [127], [127], [127] and everytime this is changing. I was also expected 1 or 2. why in this this case it was giving random state? 
2) what does hdfs_test_abnormal data covers? how it is prepared? I dont have abnormal routine database.
